import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Case Overview <a href="https://nextjs.org">CSx788977</a>
        </h1>

        <p className={styles.description}>
          Viewed @{' '}
          <code className={styles.code}>0xfdsddsxfaeafvdccd</code>
        </p>

        <div className={styles.grid}>
          <a href="/judgestage" className={styles.card2}>
            <h2>Subject</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
          <a href="https://nextjs.org/learn" className={styles.card2}>
            <h2>Party A</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
          <a href="https://nextjs.org/learn" className={styles.card2}>
            <h2>Party B</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
          <a className={styles.card2}>
            <h2>Lastest Proposal</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            <div className={styles.grid}>
                <button className={styles.button}>Accept</button>
                <button className={styles.button}>DisMiss</button>
            </div>
          </a>
        </div>
      </main>
    </div>
  )
}
