import Head from 'next/head'
import Image from 'next/image'
import { NextResponse } from 'next/server'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic";
import { utils } from "@worldcoin/id";
import Router from 'next/router'
import { WidgetProps } from "@worldcoin/id";
import { useEffect } from "react";


const WorldIDWidget = dynamic<WidgetProps>(() => import("@worldcoin/id").then((mod) => mod.WorldIDWidget), { ssr: false });


const widgetProps: WidgetProps = {
  actionId: "wid_staging_88fa0dd7349753f0188c7695b6c61029",
  signal: "user-id-1",
  enableTelemetry: true,
  appName: "ConfCon",
  signalDescription: "Get your ticket to ConfCon 2023",
  theme: "light",
  debug: true, // Recommended **only** for development
  onSuccess: (result) => Router.push('/judge'),
  onError: ({ code, detail }) => console.log({ code, detail }),
  onInitSuccess: () => console.log("Init successful"),
  onInitError: (error) => console.log("Error while initialization World ID", error),
};

export default function Judge() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Verification</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Get started by {' '}
          <code className={styles.code}>verificating yourself 🫣</code>
        </p>

        <div className={styles.grid}>
          <div id='world-id-container'>
          <WorldIDWidget {...widgetProps} />
        </div>
        </div>
      </main>
    </div>
  )
}
